version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore(deps):'
      include: 'scope'
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - '@eslint/*'
          - 'typescript*'
          - 'vite*'
          - '@sveltejs/*'
          - 'svelte-check'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        patterns:
          - 'svelte'
          - 'tailwindcss'
          - '@tailwindcss/*'
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - '@me'
    assignees:
      - '@me'
    commit-message:
      prefix: 'chore(actions):'
      include: 'scope'
