name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We love hearing your ideas.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change)
        - Medium (moderate effort)
        - Complex (major change)
        - I'm not sure
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
        - Blocker
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: Any additional information that might help us understand the feature better.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
